language: c
script: dpkg-buildpackage -b -us -uc

install:
   - sudo apt-add-repository -y ppa:pippijn/ppa
   - sudo apt-get update
   - sudo apt-get install omake noweb valgrind dh-ocaml menhir camlp4-extra libcurses-ocaml-dev libfacile-ocaml-dev libbatteries-ocaml-dev libsexplib-camlp4-dev libderiving-ocsigen-ocaml-dev
   - wget https://raw.github.com/pippijn/obuild/master/script/travis-depend?$(date +%s) -O travis-depend
   - chmod +x travis-depend
   - ./travis-depend baselib
   - cd ..
   - hg clone https://bitbucket.org/camlspotter/pa_monad_custom
   - cd pa_monad_custom
   - make
   - sudo make findlib-install
   - cd ../mlwidgets

# whitelist
branches:
   only:
      - master
      - /.*\/staging/
